name: Build and Upload aria2c

on:
  push:
    branches:
      - EX_INVALID_RANGE_HEADER
  pull_request:

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Build Docker image using dockerfile.mingw
      - name: Build Docker image
        run: docker build -t my-docker-app -f ./Dockerfile.mingw .

      # Run Docker container
      - name: Run Docker container
        run: docker run --name my-container my-docker-app

      # Copy aria2c file from container to the host
      - name: Copy aria2c from container
        run: docker cp my-container:/path/to/aria2c ./src/aria2c

      # Upload aria2c file as an artifact
      - name: Upload aria2c file
        uses: actions/upload-artifact@v3
        with:
          name: aria2c
          path: ./src/aria2c

      # Cleanup: Stop and remove the Docker container
      - name: Cleanup Docker container
        run: |
          docker stop my-container
          docker rm my-container
